import type { Actor } from "@/lib/jev/types";
import type { RiskClass } from "./risk";
import type { ConfirmationPolicy } from "./confirmation";
export type ToolMetadata = {
  family: string; allowedRoles: readonly Actor[]; riskClass: RiskClass;
  sideEffect: boolean; confirmationPolicy: ConfirmationPolicy;
  directExecutionEligible: boolean; idempotent: boolean;
};
function entry(family: string, allowedRoles: readonly Actor[], riskClass: RiskClass): ToolMetadata {
  return { family, allowedRoles, riskClass, sideEffect: riskClass !== "read_only",
    confirmationPolicy: riskClass === "financial" || riskClass === "destructive" || riskClass === "bulk_external" ? "explicit" : riskClass === "read_only" ? "none" : "contextual",
    directExecutionEligible: false, idempotent: riskClass === "read_only" };
}
/** Canonical metadata for customer, seller and admin tool catalogs. Shadow records do not enforce it. */
export const toolManifest: Record<string, ToolMetadata> = {
  addItemToOrder: entry("order", ["seller", "admin"], "reversible_write"),
  addOrderItem: entry("order", ["customer"], "reversible_write"),
  addToOrder: entry("order", ["customer"], "reversible_write"),
  broadcastWhatsApp: entry("broadcast", ["admin"], "bulk_external"),
  calculateTotal: entry("order", ["seller", "admin"], "read_only"),
  cancelOrder: entry("order", ["customer", "seller", "admin"], "destructive"),
  checkAvailability: entry("other", ["customer"], "read_only"),
  checkDelivery: entry("other", ["customer"], "read_only"),
  checkHamburguesasStock: entry("other", ["customer"], "read_only"),
  checkKitchenStatus: entry("other", ["customer"], "read_only"),
  checkPanStock: entry("other", ["customer"], "read_only"),
  checkProductAvailability: entry("product", ["customer"], "read_only"),
  confirmOrder: entry("order", ["customer", "admin"], "reversible_write"),
  createClient: entry("client", ["admin"], "business_write"),
  createDeliveredOrder: entry("order", ["seller", "admin"], "business_write"),
  createOrder: entry("order", ["customer", "seller", "admin"], "business_write"),
  createProduct: entry("product", ["admin"], "business_write"),
  deleteLead: entry("other", ["admin"], "destructive"),
  deleteProduct: entry("product", ["admin"], "destructive"),
  getActivePromos: entry("product", ["customer"], "read_only"),
  getActivePromotions: entry("product", ["seller", "admin"], "read_only"),
  getAddresses: entry("client", ["customer"], "read_only"),
  getAllProducts: entry("product", ["seller", "admin"], "read_only"),
  getAnalytics: entry("analytics", ["seller", "admin"], "read_only"),
  getAverageTicket: entry("analytics", ["seller", "admin"], "read_only"),
  getBusinessHours: entry("business_config", ["customer", "admin"], "read_only"),
  getBusinessSummary: entry("analytics", ["seller", "admin"], "read_only"),
  getClientByPhone: entry("client", ["seller", "admin"], "read_only"),
  getClientDetail: entry("client", ["seller", "admin"], "read_only"),
  getClientHistory: entry("client", ["customer", "seller", "admin"], "read_only"),
  getClients: entry("client", ["admin"], "read_only"),
  getConversationContext: entry("other", ["admin"], "read_only"),
  getConversationMessages: entry("other", ["admin"], "read_only"),
  getConversations: entry("other", ["admin"], "read_only"),
  getCustomerFullProfile: entry("client", ["seller", "admin"], "read_only"),
  getDeliveryTime: entry("other", ["customer"], "read_only"),
  getMenu: entry("product", ["customer"], "read_only"),
  getOrderById: entry("order", ["seller", "admin"], "read_only"),
  getOrderHistory: entry("order", ["seller", "admin"], "read_only"),
  getOrderStatus: entry("order", ["customer", "seller", "admin"], "read_only"),
  getOrderSummary: entry("order", ["customer"], "read_only"),
  getPaymentAlias: entry("other", ["customer"], "read_only"),
  getPendingOrders: entry("order", ["seller", "admin"], "read_only"),
  getProductAvailability: entry("product", ["seller", "admin"], "read_only"),
  getProductById: entry("product", ["seller", "admin"], "read_only"),
  getProductDetails: entry("product", ["customer"], "read_only"),
  getProductPrice: entry("product", ["customer"], "read_only"),
  getProductsByCategory: entry("product", ["seller", "admin"], "read_only"),
  getSalesByDateRange: entry("analytics", ["seller", "admin"], "read_only"),
  getTodaysOrders: entry("order", ["seller", "admin"], "read_only"),
  getTopClients: entry("client", ["seller", "admin"], "read_only"),
  getTopProducts: entry("product", ["seller", "admin"], "read_only"),
  getWaitTime: entry("other", ["customer"], "read_only"),
  injectCustomerNote: entry("client", ["seller", "admin"], "reversible_write"),
  listAvailableProducts: entry("product", ["customer"], "read_only"),
  markAsPaid: entry("payment", ["seller", "admin"], "financial"),
  markPaymentMethod: entry("payment", ["seller", "admin"], "financial"),
  queryData: entry("other", ["admin"], "read_only"),
  removeItemFromOrder: entry("order", ["admin"], "destructive"),
  saveAddress: entry("client", ["customer"], "reversible_write"),
  searchClient: entry("client", ["seller", "admin"], "read_only"),
  searchOrdersByDate: entry("order", ["admin"], "read_only"),
  searchProducts: entry("product", ["customer", "seller", "admin"], "read_only"),
  sendDocument: entry("outbound_message", ["customer"], "external_message"),
  sendImage: entry("outbound_message", ["customer"], "external_message"),
  sendMenuImage: entry("outbound_message", ["customer"], "external_message"),
  sendMessageAsOperator: entry("outbound_message", ["admin"], "external_message"),
  sendProductImage: entry("outbound_message", ["customer"], "external_message"),
  sendPromoImage: entry("outbound_message", ["customer"], "external_message"),
  sendSticker: entry("outbound_message", ["customer"], "external_message"),
  sendWhatsAppMessage: entry("outbound_message", ["seller", "admin"], "external_message"),
  setClientAlias: entry("client", ["admin"], "reversible_write"),
  setHumanOverride: entry("other", ["admin"], "destructive"),
  suggestProducts: entry("product", ["customer", "admin"], "read_only"),
  transferToHuman: entry("outbound_message", ["customer"], "external_message"),
  updateAgentConfig: entry("business_config", ["admin"], "reversible_write"),
  updateBusinessHours: entry("business_config", ["admin"], "reversible_write"),
  updateClient: entry("client", ["seller", "admin"], "reversible_write"),
  updateOrder: entry("order", ["customer"], "reversible_write"),
  updateOrderStatus: entry("order", ["seller", "admin"], "reversible_write"),
  updateOrderStatusNew: entry("order", ["admin"], "reversible_write"),
  updateProduct: entry("product", ["admin"], "reversible_write"),
};
export function toolAllowed(name: string, actor: Actor): boolean {
  return toolManifest[name]?.allowedRoles.includes(actor) === true;
}
